#!/usr/bin/env bash
# Regenerates nginx/cloudflare-real-ip.conf from Cloudflare's published IP ranges so the
# `set_real_ip_from` trust list never has to be hand-maintained. Run it locally before committing,
# in CI, or on the VPS during deploy (see deploy/pull-and-restart.sh). The generated file is
# gitignored and `include`d by nginx/nginx.conf.
#
# Usage:
#   deploy/update-cloudflare-ips.sh [output-file]
#
# Exit codes: 0 = file written or already current, non-zero = fetch/validation failed (existing
# file is left untouched so a bad fetch can never wipe a working trust list).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${1:-${SCRIPT_DIR}/../nginx/cloudflare-real-ip.conf}"

# Docker creates a missing bind-mount source as a root-owned *directory*, so if nginx ever started
# before this file was generated, ${OUT} is now a directory the deploy user can't `mv` onto.
if [ -d "${OUT}" ]; then
	echo "ERROR: ${OUT} is a directory, not a file — Docker created it as a bind-mount source" >&2
	echo "before the trust list was generated. Remove it and re-run: sudo rm -rf '${OUT}'" >&2
	exit 1
fi

V4_URL="https://www.cloudflare.com/ips-v4"
V6_URL="https://www.cloudflare.com/ips-v6"

# Matches an IPv4 or IPv6 CIDR. Anything that doesn't look like a CIDR (e.g. an HTML error page)
# is rejected before we overwrite the existing, known-good file.
CIDR_RE='^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$|^[0-9a-fA-F:]+/[0-9]{1,3}$'

fetch() {
	# -f: fail on HTTP errors, -sS: quiet but show errors, -L: follow redirects.
	curl -fsSL --max-time 15 --retry 3 --retry-delay 2 "$1"
}

echo "Fetching Cloudflare IP ranges..."
ranges="$(fetch "${V4_URL}"; echo; fetch "${V6_URL}")"

# Drop blank lines and validate every remaining line is a CIDR before trusting the payload.
cidrs="$(printf '%s\n' "${ranges}" | sed '/^[[:space:]]*$/d')"
if [ -z "${cidrs}" ]; then
	echo "ERROR: Cloudflare returned an empty range list; keeping existing file." >&2
	exit 1
fi
while IFS= read -r line; do
	if ! printf '%s' "${line}" | grep -Eq "${CIDR_RE}"; then
		echo "ERROR: unexpected line from Cloudflare (not a CIDR): '${line}'. Keeping existing file." >&2
		exit 1
	fi
done <<<"${cidrs}"

tmp="$(mktemp)"
trap 'rm -f "${tmp}"' EXIT
{
	echo "# Generated by deploy/update-cloudflare-ips.sh - do not edit by hand."
	echo "# Source: ${V4_URL} and ${V6_URL}"
	echo "# Regenerate with: deploy/update-cloudflare-ips.sh"
	printf '%s\n' "${cidrs}" | sed 's/^/set_real_ip_from /; s/$/;/'
} >"${tmp}"

if [ -f "${OUT}" ] && cmp -s "${tmp}" "${OUT}"; then
	echo "Cloudflare ranges unchanged: ${OUT}"
	exit 0
fi

mv "${tmp}" "${OUT}"
trap - EXIT
echo "Wrote $(grep -c '^set_real_ip_from' "${OUT}") ranges to ${OUT}"
